//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServicioMecanico.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Car()
        {
            this.ServicesCars = new HashSet<ServicesCar>();
        }
    
        public int IdCar { get; set; }
        public int IdCarBrand { get; set; }
        public string YearCar { get; set; }
        public string LicensePlate { get; set; }
        public string Observations { get; set; }
        public Nullable<int> IdOwner { get; set; }
    
        public virtual CarBrand CarBrand { get; set; }
        public virtual Owner Owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicesCar> ServicesCars { get; set; }
    }
}
